### ISSUE TITLE
ERRO[0849] error waiting for container: context canceled

### ISSUE THREAD

**Issue by flexboni** [eungbean/Docker-for-AI-Researcher#1]
```
sudo docker run --gpus all -it \
-p 7000:8080 -p 7006-7015:6006-6015 \
-v ~/docker:/data \
--name code \
-e PASSWORD="0000" \
--ipc=host eungbean/deepo:code /coder/code-server
```
위 명령어를 입력했는데 제목과 같은 에러가 떠서 어떻게 해야할지 모르겠어서 이슈 등록했습니다.

> 우분투 20.04 환경에서 진행했습니다.

**Comment by IMCHO** [comment]
우분투에서 같은 오류가 발생하네요..! 해결하셨나요?

**Comment by flexboni** [comment]
> 우분투에서 같은 오류가 발생하네요..! 해결하셨나요?

아뇨.. ㅠ.ㅠ 포기했습니다.
우분투 버전을 내려보던가 해야겠어요

**Comment by eungbean** [comment]
Thank you for your participation.
All errors are fixed now.🙏
