### ISSUE TITLE
./SETTINGS.sh cannot open, ./INSTALL.sh cannot install

### ISSUE THREAD

**Issue by LEESHOHYUN** [eungbean/Docker-for-AI-Researcher#3]
I tried to install but cannot install 
as I tried ./SETTINGS and nothing comes out
as I tried ./INSTALL and 

Unable to find image 'deepo:code' locally
docker: Error response from daemon: pull access denied for deepo, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

above error code comes out
 
may I ask how to solve the problem??

**Comment by eungbean** [comment]
Thank you for your participation.
All errors are fixed now.🙏
