### ISSUE TITLE
Unresolved merge conflict in /scripts/1-basic_install.sh

### ISSUE THREAD

**Issue by yerachoi** [eungbean/Docker-for-AI-Researcher#4]
Hello! I'd first like to thank you for sharing this convenient repo. 
I believe that there is an unresolved merge conflict in /scripts/1-basic_install.sh (lines 3-8), and hope it gets fixed later.

```
<<<<<<< HEAD:scripts/1-basic_install.sh
source ${PROJ_DIR}/CONFIGS.sh

=======
source ${PROJ_DIR}/SETTINGS.sh
>>>>>>> origin/master:scripts/1-terminal_setting.sh

**Comment by eungbean** [comment]
Thank you for your participation.
All errors are fixed now.🙏
